title: Creaci贸n de un juego de simulaci贸n interactivo seguro en realidad virtual inmersiva como herramienta de rehabilitaci贸n para paciente que padecen de heminegligencia
<h2>Proyecto de titulaci贸n</h2>
<h3>Alejandra Witto Royo</h3>
#logo: /assets/img/img.png
#description: texto bajo la imagen
show_downloads: false
theme: jekyll-theme-minimal
