title: Creaci贸n de un juego de simulaci贸n interactivo seguro en realidad virtual inmersiva como herramienta de rehabilitaci贸n para paciente que padecen de heminegligencia
subtitle: Proyecto de titulaci贸n
subtitle: Alejandra Witto Royo
#logo: /assets/img/img.png
#description: texto bajo la imagen
show_downloads: false
theme: jekyll-theme-minimal
